import { Link } from 'react-router-dom';

export const Spinner = ({ label = 'Loading…' }) => (
  <div className="flex items-center justify-center gap-3 py-16 text-slate-500">
    <span className="h-5 w-5 animate-spin rounded-full border-2 border-slate-300 border-t-brand-600" />
    {label}
  </div>
);

export const EmptyState = ({ title = 'Nothing here yet', subtitle, action }) => (
  <div className="card flex flex-col items-center gap-2 p-10 text-center">
    <div className="text-4xl">🗂️</div>
    <h3 className="text-lg font-semibold text-slate-700">{title}</h3>
    {subtitle && <p className="max-w-md text-sm text-slate-500">{subtitle}</p>}
    {action}
  </div>
);

export const ErrorNote = ({ message }) => (
  <div className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{message}</div>
);

/* AI-generated content must always be labeled (project AI principles). */
export const AIBadge = ({ children = 'AI-generated' }) => (
  <span className="badge bg-violet-100 text-violet-700" title="Generated by AI — please verify">
    ✨ {children}
  </span>
);

const TRUST = {
  student_submitted: { label: 'Student Submitted', cls: 'bg-slate-100 text-slate-600' },
  verified: { label: 'Verified', cls: 'bg-emerald-100 text-emerald-700' },
  official: { label: 'Official', cls: 'bg-brand-100 text-brand-700' },
};
export const TrustBadge = ({ level }) => {
  const t = TRUST[level] || TRUST.student_submitted;
  return <span className={`badge ${t.cls}`}>{level === 'verified' ? '✓ ' : ''}{t.label}</span>;
};

export const Chip = ({ children, active, ...props }) => (
  <button
    className={`rounded-full border px-3 py-1 text-xs font-medium transition ${
      active ? 'border-brand-600 bg-brand-600 text-white' : 'border-slate-200 bg-white text-slate-600 hover:bg-slate-50'
    }`}
    {...props}
  >
    {children}
  </button>
);

export const SectionHeader = ({ title, subtitle, to, linkLabel = 'View all' }) => (
  <div className="mb-4 flex items-end justify-between">
    <div>
      <h2 className="text-xl font-bold text-slate-900">{title}</h2>
      {subtitle && <p className="text-sm text-slate-500">{subtitle}</p>}
    </div>
    {to && <Link to={to} className="text-sm font-semibold text-brand-600 hover:underline">{linkLabel} →</Link>}
  </div>
);
